integration_tests_postgres:
  target: postgres
  outputs:
    postgres:
      type: postgres
      host: localhost
      user: newuser
      pass: password
      port: 5432
      dbname: test_database
      schema: set_similarity_integration_tests_postgres
      threads: 1

integration_tests_duckdb:
  target: dev
  outputs:
    dev:
      type: duckdb
      path: "../duckdb/test_database.duckdb"
