integration_tests_postgres:
  target: postgres
  outputs:
    postgres:
      type: postgres
      host: localhost
      user: newuser
      pass: password
      port: 5432
      dbname: test_database
      schema: set_similarity_integration_tests_postgres
      threads: 1

integration_tests_duckdb:
  target: dev
  outputs:
    dev:
      type: duckdb
      path: "../duckdb/test_database.duckdb"

integration_tests_sqlite:
  target: sqlite
  outputs:
    sqlite:
      type: sqlite
      threads: 1
      database: "database"
      schema: "main"
      schemas_and_paths:
        main: "../sqlite/test_database.db"
      schema_directory: "file_path"
