integration_tests:
  target: postgres
  outputs:
    postgres:
      type: postgres
      host: localhost
      user: newuser
      pass: password
      port: 5432
      dbname: test_database
      schema: set_similarity_integration_tests_postgres
      threads: 1
